#209 update with edits as submitted to LSP
wmo-im/wcmp2 pull request #210
Opened 2024-07-23 15:04 UTC by amilan17

#209

2024-07-23 15:06 UTC, amilan17 commented
@tomkralidis - please review the changes in clause 7 and ignore the other diffs: https://github.com/wmo-im/wcmp2/pull/210/files#diff-ec717b6546ff6063369d5b07d05f9d101cb950ef1646da0ae885050de6c2ae0f

2024-07-26 07:18 UTC, amilan17 commented on standard/requirements/core/REQ_record_creation_date.adoc
> +^|B |The `+properties.created+` property SHALL not be repeated or used to document change history.
```suggestion
^|B |The `+properties.created+` property SHALL NOT be repeated or used to document change history.
```

2024-07-26 07:18 UTC, amilan17 commented on standard/sections/annex_d_codelists.adoc
> +The links below provide some controlled vocabularies in support of dataset status, and MAY be
```suggestion
The links below provide some controlled vocabularies in support of dataset status, and may be
```

2024-07-26 07:19 UTC, amilan17 commented on standard/sections/clause_0_front_material.adoc
> +WCMP documents SHALL be encoded in GeoJSON (RFC 7946 footnote:[https://datatracker.ietf.org/doc/html/rfc7946]) as
```suggestion
WCMP documents shall be encoded in GeoJSON (RFC 7946 footnote:[https://datatracker.ietf.org/doc/html/rfc7946]) as
```

2024-07-26 07:19 UTC, amilan17 commented on standard/sections/clause_0_front_material.adoc
> +defined in this specification and SHALL be made available as HTTP crawlable files or via API provisioning as defined
```suggestion
defined in this specification and shall be made available as HTTP crawlable files or via API provisioning as defined
```

2024-07-26 07:19 UTC, amilan17 commented on standard/sections/clause_0_front_material.adoc
> +Based on the WMO Unified Data Policy for the International Exchange of Earth System Data (Resolution 1 (Cg-Ext(2021) footnote:[https://library.wmo.int/doc_num.php?explnum_id=11113#page=9], exchanged
```suggestion
Based on the WMO Unified Data Policy for the International Exchange of Earth System Data (Resolution 1 (Cg-Ext(2021) footnote:[https://library.wmo.int/doc_num.php?explnum_id=11113#page=9], exchanged data are classified as `+core+` or `+recommended+`.  Core data is considered fully open and unrestricted with no security considerations.  Recommended data may have access control defined.
```

2024-07-26 07:20 UTC, amilan17 commented on standard/sections/clause_1_scope.adoc
> +WCMP discovery metadata records SHALL be encoded as GeoJSON as defined in _OGC API - Records - Part 1: Core_.
```suggestion
WCMP discovery metadata records shall be encoded as GeoJSON as defined in _OGC API - Records - Part 1: Core_.
```

2024-07-26 07:20 UTC, amilan17 commented on standard/sections/clause_1_scope.adoc
> +MAY be represented as part of their own metadata or associated through WCMP links.
```suggestion
may be represented as part of their own metadata or associated through WCMP links.
```

2024-07-26 07:20 UTC, amilan17 commented on standard/sections/clause_2_conformance.adoc
> +Conformance with this standard SHALL be checked using the tests specified in Annex A (normative) of this document.
```suggestion
Conformance with this standard shall be checked using the tests specified in Annex A (normative) of this document.
```

2024-07-26 07:21 UTC, amilan17 commented on standard/sections/clause_2_conformance.adoc
> +WMO Core Metadata Profile (WCMP).  WCMP discovery metadata SHALL therefore be compliant with OGC API - Records - Part 1:
```suggestion
WMO Core Metadata Profile (WCMP).  WCMP discovery metadata shall therefore be compliant with OGC API - Records - Part 1:
```

2024-07-26 07:21 UTC, amilan17 commented on standard/sections/clause_2_conformance.adoc
> +WMO SHALL publish guidance material to assist authors of WCMP discovery metadata for maintaining
```suggestion
WMO shall publish guidance material to assist authors of WCMP discovery metadata for maintaining
```

2024-07-26 07:27 UTC, amilan17 commented on standard/sections/clause_8_gdc.adoc
> +workflow, a GDC MAY choose to apply filters to help narrow search results.  This is realized by
```suggestion
workflow, a GDC may choose to apply filters to help narrow search results.  This is realized by
```

2024-07-26 07:28 UTC, amilan17 commented on standard/sections/clause_8_gdc.adoc
> +MAY choose to apply facets to WCMP records.  Facets are effective when applied against controlled
```suggestion
may choose to apply facets to WCMP records.  Facets are effective when applied against controlled
```

2024-07-29 12:07 UTC, amilan17 commented on standard/sections/clause_7_normative_text.adoc
> +== Appendix F: WMO Core Metadata Profile (Version 2)
```suggestion
== Appendix F: WMO Core Metadata Profile (Version 2)
```
```suggestion
== WMO Core Metadata Profile (Version 2)
```

2024-07-29 12:33 UTC, amilan17 commented on standard/recommendations/core/REC_pids.adoc
> +//rec9
```suggestion
//rec10
```

2024-07-30 01:35 UTC, tomkralidis requested changes
See change requests. As well, need to review/assess #214/#215 in relation to this PR.

2024-07-30 01:35 UTC, tomkralidis commented on standard/sections/clause_7_normative_text.adoc
> + by link:https://www.iana.org/assignments/link-relations/link-relations.xhtml[IANA link relations] or link:https://codes.wmo.int/wis/link-type[WIS link type] extensions. (see table <<_link_relation_s
```suggestion
 by link:https://www.iana.org/assignments/link-relations/link-relations.xhtml[IANA link relations] or link:https://codes.wmo.int/wis/link-type[WIS link type] extensions. (see table <<_1_19_5_link_relation_selection>>)
```

2024-07-30 01:35 UTC, tomkralidis commented on standard/sections/clause_8_gdc.adoc
Links in this file need to be updated as follows:

```diff
diff --git a/standard/sections/clause_8_gdc.adoc b/standard/sections/clause_8_gdc.adoc
index 7ad9cda..a0ddda8 100644
--- a/standard/sections/clause_8_gdc.adoc
+++ b/standard/sections/clause_8_gdc.adoc
@@ -13,5 +13,5 @@ may choose to apply facets to WCMP records.  Facets are effective when applied a
 vocabularies and classifications.  The following WCMP required properties would be subject to faceting by a GDC:
 
 - ``centre-id`` as defined in <<_identifier>>
-- <<_properties_type>>
-- <<_properties_wmo_data_policy>>
+- <<_1_6_properties_type>>
+- <<_1_18_properties_wmo_data_policy>>
```

2024-07-31 12:16 UTC, amilan17 commented on standard/sections/clause_7_normative_text.adoc
> +Note: This section of working draft document is the same as Appendix F in the https://library.wmo.int/idurl/4/68731[_Manual on the WMO Information System_] (WMO-No. 1060), Volume II
```suggestion
Note: This section of working draft document is the same as Appendix F in the https://library.wmo.int/idurl/4/68731[_Manual on the WMO Information System_] (WMO-No. 1060), Volume II.
```

2024-08-02 11:30 UTC, tomkralidis approved these changes

2024-08-02 11:30 UTC, merged